# Generated by Django 2.1.1 on 2018-09-08 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCat', models.CharField(max_length=30)),
                ('FechaCreacion', models.DateField(default='2000-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=30)),
                ('Costo', models.DateField(default='2000-01-01')),
                ('Disponible', models.BooleanField(default=0)),
                ('NumExistencia', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
